
CREATE TABLE Cameras (
    CameraID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    IP_Address VARCHAR2
(15) NOT NULL,
    Location_Name VARCHAR2
(100),
    Status VARCHAR2
(20) DEFAULT 'ACTIVE',
    Date_Added DATE DEFAULT SYSDATE
);


CREATE TABLE EVENTS (
    Event_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Camera_ID NUMBER REFERENCES Cameras
(CameraID),
    Timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Alert_Type VARCHAR2
(50),
    Object_Class VARCHAR2
(50) NOT NULL,
    Confidence_Score NUMBER
(4, 2), 
    Video_Clip_Path VARCHAR2
(255)
);


CREATE OR REPLACE TRIGGER Validate_Camera_IP
BEFORE
INSERT OR
UPDATE ON Cameras
FOR EACH ROW
BEGIN
    IF NOT REGEXP_LIKE(:NEW.IP_Address, '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$') THEN
        RAISE_APPLICATION_ERROR
    (-20001, 'Invalid IP Address format. Must match local subnet routing.');
END
IF;
END;
/